
import React, { useEffect, useState } from "react";
import { View, Text, ActivityIndicator, StyleSheet } from "react-native";
import { Platform } from "react-native";
import Constants from "expo-constants";

type Status = "processing" | "success" | "error";

export default function AuthCallbackScreen() {
  const [status, setStatus] = useState<Status>("processing");
  const [message, setMessage] = useState("Processing authentication...");

  useEffect(() => {
    if (Platform.OS !== "web") return;
    handleCallback();
  }, []);

  const handleCallback = async () => {
    try {
      const urlParams = new URLSearchParams(window.location.search);
      const betterAuthToken = urlParams.get("better_auth_token");
      const error = urlParams.get("error");

      console.log("[AuthCallback] URL:", window.location.href);
      console.log("[AuthCallback] better_auth_token present:", !!betterAuthToken);
      console.log("[AuthCallback] Error:", error);

      if (error) {
        console.error("[AuthCallback] OAuth error:", error);
        setStatus("error");
        setMessage(`Authentication failed: ${error}`);
        if (window.opener) {
          window.opener.postMessage({ type: "oauth-error", error }, window.location.origin);
        }
        setTimeout(() => window.close(), 2000);
        return;
      }

      if (!betterAuthToken) {
        console.error("[AuthCallback] No better_auth_token in URL");
        setStatus("error");
        setMessage("No authentication token received");
        if (window.opener) {
          window.opener.postMessage(
            { type: "oauth-error", error: "No authentication token received" },
            window.location.origin
          );
        }
        setTimeout(() => window.close(), 2000);
        return;
      }

      // The better_auth_token is a one-time token from Better Auth's OAuth flow.
      // Better Auth's authClient.getSession() automatically reads better_auth_token
      // from the current page URL and exchanges it for a real session.
      // This MUST happen in the popup window (auth-callback) because the token
      // is in THIS window's URL.
      console.log("[AuthCallback] Exchanging better_auth_token for session...");
      
      const BACKEND_URL = Constants.expoConfig?.extra?.backendUrl || "";
      
      let sessionToken: string | null = null;
      let userData: any = null;
      
      // Exchange better_auth_token for a real session
      // The better_auth_token is a one-time token generated by Better Auth after OAuth
      // We try multiple approaches to exchange it for a real session token
      console.log("[AuthCallback] Starting token exchange for better_auth_token (length:", betterAuthToken.length, ")");
      
      // IMPORTANT: Clear any stored Bearer token first to avoid interference
      localStorage.removeItem("cheshbon_bearer_token");
      
      // Approach 1: Direct fetch to /api/auth/get-session with better_auth_token as query param
      // This is the standard Better Auth token exchange endpoint
      try {
        const sessionResponse = await fetch(
          `${BACKEND_URL}/api/auth/get-session?better_auth_token=${encodeURIComponent(betterAuthToken)}`,
          {
            method: "GET",
            credentials: "include",
          }
        );
        
        const rawText = await sessionResponse.text();
        console.log("[AuthCallback] /api/auth/get-session?better_auth_token status:", sessionResponse.status, "body:", rawText.substring(0, 300));
        
        if (sessionResponse.ok && rawText) {
          try {
            const parsed = JSON.parse(rawText);
            if (parsed?.user) {
              userData = parsed.user;
              sessionToken = parsed?.session?.token || betterAuthToken;
              console.log("[AuthCallback] Session established via get-session query param");
            } else {
              console.warn("[AuthCallback] get-session returned no user:", JSON.stringify(parsed).substring(0, 200));
            }
          } catch (parseErr) {
            console.warn("[AuthCallback] Failed to parse get-session response:", parseErr);
          }
        }
      } catch (err) {
        console.warn("[AuthCallback] /api/auth/get-session fetch failed:", err);
      }
      
      // Approach 2: Try /api/auth/get-session with Bearer header
      if (!userData) {
        try {
          const sessionResponse = await fetch(
            `${BACKEND_URL}/api/auth/get-session`,
            {
              method: "GET",
              credentials: "include",
              headers: {
                "Authorization": `Bearer ${betterAuthToken}`,
              },
            }
          );
          
          const rawText = await sessionResponse.text();
          console.log("[AuthCallback] /api/auth/get-session Bearer status:", sessionResponse.status, "body:", rawText.substring(0, 300));
          
          if (sessionResponse.ok && rawText) {
            try {
              const parsed = JSON.parse(rawText);
              if (parsed?.user) {
                userData = parsed.user;
                sessionToken = parsed?.session?.token || betterAuthToken;
                console.log("[AuthCallback] Session established via get-session Bearer");
              }
            } catch (parseErr) {
              console.warn("[AuthCallback] Failed to parse get-session Bearer response:", parseErr);
            }
          }
        } catch (err) {
          console.warn("[AuthCallback] /api/auth/get-session Bearer failed:", err);
        }
      }
      
      // Approach 3: Try /api/auth/me with Bearer token
      if (!userData) {
        try {
          const meResponse = await fetch(
            `${BACKEND_URL}/api/auth/me`,
            {
              method: "GET",
              credentials: "include",
              headers: {
                "Authorization": `Bearer ${betterAuthToken}`,
              },
            }
          );
          
          const rawText = await meResponse.text();
          console.log("[AuthCallback] /api/auth/me status:", meResponse.status, "body:", rawText.substring(0, 300));
          
          if (meResponse.ok && rawText) {
            try {
              const parsed = JSON.parse(rawText);
              if (parsed?.user) {
                userData = parsed.user;
                sessionToken = parsed?.session?.token || betterAuthToken;
                console.log("[AuthCallback] Session established via /api/auth/me");
              }
            } catch (parseErr) {
              console.warn("[AuthCallback] Failed to parse /api/auth/me response:", parseErr);
            }
          }
        } catch (err) {
          console.warn("[AuthCallback] /api/auth/me fetch failed:", err);
        }
      }
      
      const isPopup = !!window.opener;
      
      if (userData && sessionToken) {
        // Store the real session token in localStorage
        // (localStorage is shared between popup and parent on same origin)
        localStorage.setItem("cheshbon_bearer_token", sessionToken);
        
        console.log("[AuthCallback] Authentication successful");
        setStatus("success");
        setMessage("Authentication successful! Closing...");
        
        if (isPopup) {
          // Popup mode: notify parent window
          window.opener.postMessage(
            { 
              type: "oauth-success", 
              token: sessionToken,
              user: userData,
            },
            window.location.origin
          );
          setTimeout(() => window.close(), 1000);
        } else {
          // Redirect mode: navigate to home page
          console.log("[AuthCallback] Redirect mode, navigating to home...");
          setTimeout(() => {
            window.location.href = "/";
          }, 500);
        }
      } else {
        // If we couldn't exchange the token in the popup, pass the better_auth_token
        // The parent window will try all approaches to exchange it
        console.log("[AuthCallback] Could not exchange token, passing better_auth_token for exchange");
        setStatus("success");
        setMessage("Authentication successful! Closing...");
        
        if (isPopup) {
          window.opener.postMessage(
            { type: "oauth-success", token: betterAuthToken, user: null },
            window.location.origin
          );
          setTimeout(() => window.close(), 1000);
        } else {
          // Redirect mode: store the better_auth_token and navigate to home
          // The home page's AuthProvider will try to exchange it
          localStorage.setItem("cheshbon_bearer_token", betterAuthToken);
          setTimeout(() => {
            window.location.href = "/";
          }, 500);
        }
      }
    } catch (err) {
      console.error("[AuthCallback] Error processing callback:", err);
      setStatus("error");
      setMessage("Failed to process authentication");
      if (window.opener) {
        window.opener.postMessage(
          { type: "oauth-error", error: "Failed to process authentication" },
          window.location.origin
        );
      }
      setTimeout(() => window.close(), 2000);
    }
  };

  return (
    <View style={styles.container}>
      {status === "processing" && <ActivityIndicator size="large" color="#007AFF" />}
      {status === "success" && <Text style={styles.successIcon}>✓</Text>}
      {status === "error" && <Text style={styles.errorIcon}>✗</Text>}
      <Text style={styles.message}>{message}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#fff",
  },
  successIcon: {
    fontSize: 48,
    color: "#34C759",
  },
  errorIcon: {
    fontSize: 48,
    color: "#FF3B30",
  },
  message: {
    fontSize: 18,
    marginTop: 20,
    textAlign: "center",
    color: "#333",
  },
});
